### ISSUE TITLE
General Time Estimate?

### ISSUE THREAD

**Issue by CyberFox2795** [BurnhamR/McHeli2#8]
Is there a new general estimate on when things will be ready for release?

**Comment by HileyNoteson** [comment]
If you can fix the errors in the code, you can use intellj or eclipse to compile it. see my ticket for more info

**Comment by CyberFox2795** [comment]
I can give it a shot, I have a bit of experience in java programming but nothing much. I was wondering if there was a ballpark for official release?

**Comment by RamennBowls** [comment]
The thing about compiling this public repo, is that its not up-to-date... It's better than nothing but knowing that they were working on things in a private repo I'm sure this is out-of-date by over 6 months.

**Comment by CyberFox2795** [comment]
Dang alright, I think I'll just wait until full release then. 6 months of work is a LOT of programing we are missing out on. Wish we had some kind of communication line with the devs to find out how things are progressing.

**Comment by RamennBowls** [comment]
> Dang alright, I think I'll just wait until full release then. 6 months of work is a LOT of programing we are missing out on. Wish we had some kind of communication line with the devs to find out how things are progressing.

If you see issue #7, we wanted to compile what we had of the mod and ran into some issues but after some investigating there's hardly any code here, there's a lot of empty placeholder code for classes that don't exist in this public repo so I presume this public repo is like 1% of the actual mod. It's only 250kb and even after fixing all the issues there's hardly any code or content.

I hope the developers are still working or will at least make what ever they have publicly available as apparently it was 75% done as stated in issue #1.

**Comment by RamennBowls** [comment]
Doing a little bit of stalking 👀, their Github says that yesterday there were "8 contributions in private repositories" which could be for MCHeli2
![image](https://user-images.githubusercontent.com/28948494/125728279-d9b38cdc-bede-4c83-b393-1bff3c69e0ba.png)

**Comment by Xanton19** [comment]
@RamennBowls You are completely right, thats what I was thinking too, when I was following this Repo closely since almost its inception (December 2020), hence the posting of #1 .

I also suppose that the contributions to the private repos might be related to MCHeli2, as the developer mentioned that this repository may not be updated frequently, due to it only reciving large mod updates, and a private repo between the developers of the Mod to work on it together.

Speaking from experience, completing the last few Percent of the mod might actually be really hard, especially with complex and large ports like MCHeli (I have decompiled MCHeli 1.7.10 to see the Sources and Files, and the amount of complex logic programmed into MCHeli is huge and the current, outdated Repo with just a few java files is nothing compared to the 1.7.10 Version), another reason to why it might not progress as fast is that the developers may be lacking the time and energy to invest in to the MCHeli port.

Anyway, the increase in contributions (If we assume it is related to MCHeli2) might indicate that the mod maybe soon completed, which would be amazing, otherwise it would be awesome if the current status of the code can be made public to this MCHeli2 repo, so we are able to contribute to the Project.

This is not really related to this Issue, but I have found a while ago a stable API that is Minecraft agnostic to develop mods, which is called "[UniversalModCore](https://github.com/TeamOpenIndustry/UniversalModCore)".

This allows developers to have to write the code for the mod once, while not needing to worry about supporting the many Minecraft versions out there, as you can currently compile the mod from the 1.7.10 version up to the 1.16.4 version with the same code, which in theory would eliminate the need of porting the mod to a newer/older Minecraft version, as the only thing that has to be ported is the UniversalModCore itself.

**Comment by BurnhamR** [comment]
For all further discussions please use the new discussion tab! Thanks!
